### ISSUE TITLE
Copy rebar - copy to multiple objects

### ISSUE THREAD

**Issue by alekhanssen** [eibre/EiBreRebarUtils#1]
Would be nice to be able to copy rebar to multiple elements rather than just one at a time!

**Comment by eibre** [comment]
@alekhanssen Er det best med to forskjellige copy funksjoner, eller tror du det er like greit med én? Problemet med å kunne velge flere er at man må huske å trykke på den lille "Finish" knappen helt oppe i venstre hjørne. Se https://github.com/eibre/EiBreRebarUtils/pull/2 for screenshot

**Comment by alekhanssen** [comment]
Sikkert like greit med en funksjon
