### ISSUE TITLE
New feature wanted - Dissallow join simplification

### ISSUE THREAD

**Issue by alekhanssen** [eibre/EiBreRebarUtils#5]
Sikkert litt utenfor oppgaven til et rebar tool, men en forenkling av disallow join hadde vært konge

Tenkt bruk: Trykk på en knapp (eller KS), velg element. Så blir begge ender disallowed.

Det som må skje bak vet jeg ikke noe om...

**Comment by eibre** [comment]
Wish granted: 
![image](https://user-images.githubusercontent.com/5968613/63973538-45c0ea80-caab-11e9-8718-aac30176c5c0.png)

**Comment by eibre** [comment]
https://github.com/eibre/EiBreRebarUtils/commit/be7c997c14c9b8c60c8ae4170d901e4f386f0e38
